#!/bin/bash

export PS1="\[\e[35;1m\]\u\[\e[0m\]@\[\e[32;1m\]\h\[\e[0m\]:\[\e[37m\][\w]\[\e[35;1m\]\n\[\e[31;1m\]\$ \[\e[0m\]"

_sbt() {
    LOCAL="conf/env/local.conf"
    SBT_FLAGS="-mem 2048 -Dehcacheplugin=disabled -Dmemcachedplugin=enabled -Dauth.sessionTimeout=604800"

    if [[ -e $LOCAL ]]; then
        FLAGS="-Dconfig.file=$LOCAL $FLAGS"
    fi

    /usr/bin/sbt $FLAGS $@
}

sbt() {
    TZ=UTC _sbt $@
}

sbt_email() {
    sbt -Demails.enabled=true -Dsmtp.mock=false -Dsmtp.port=1025 $@
}

sbt_notz() {
    _sbt $@
}


export ANDROID_HOME=$HOME/Android/Sdk

npm_bin() {
    export PATH=`npm bin`:$PATH
}

for file in $(ls $HOME/shared/bash); do
    if [[ $file == "aliases.bash" ]]; then
        ## just in case its renamed aliases.bash to prevent a recursive bash sourcing
        continue
    fi

    if [[ "${file##*.}" == "bash" ]]; then
        source $HOME/shared/bash/$file
    fi
done
