#!/bin/bash

export PS1="\[\e[35;1m\]\u\[\e[0m\]@\[\e[32;1m\]\h\[\e[0m\]:\[\e[37m\][\w]\[\e[35;1m\]\n\[\e[31;1m\]\$ \[\e[0m\]"

SBT_FLAGS="-mem 2048 -Dehcacheplugin=disabled -Dmemcachedplugin=enabled -Dauth.sessionTimeout=604800"
alias sbt="TZ='UTC' sbt $SBT_FLAGS"
alias sbt_email="TZ='UTC' sbt $SBT_FLAGS -Demail.enabled=true -Dsmtp.mock=false -Dsmtp.port=1025"
alias sbt_notz="sbt $SBT_FLAGS"

for file in $(ls $HOME/shared/bash); do
    if [[ $file == "aliases.bash" ]]; then
        ## just in case its renamed aliases.bash to prevent a recursive bash sourcing
        continue
    fi

    if [[ "${file##*.}" == "bash" ]]; then
        source $HOME/shared/bash/$file
    fi
done
